### ISSUE TITLE
Audio breaks after reboot

### ISSUE THREAD

**Issue by FluffyCyanFox** [annabelsandford/Mac_Windows_GPU_Disabler#1]
When initially running the program, audio is restored, but after performing a reboot, audio is lost again. All startup processes are enabled, so audio should be enabled at start. Possibly the audio fix could be made to run independently from the GPU Disabler and have its own startup process. This would also allow people to install just the audio fix and keep the GPU drivers if they want to.

There seems to be no other software that restores audio as conveniently as this, so it would be great if you could look into this issue. Thanks.

MacBook Pro (9,2) 2012 13" (A1278)

**Comment by annabelsandford** [comment]
That's an extremely odd issue considering the Audio Overwrite is (or should be) permanent. 
What the Audio Fix does is create, compile and apply a custom Audio Driver - thus the Audio Fix is a rather "time taking" operation.

Ofc I can give the option to run the Audio Fix independently from the GPU Disabler when I have some time to look into the codebase again, but actually I'm a little concerned about your machine always overwriting your Audio Drivers.
You should definitely look into that.

**Comment by FluffyCyanFox** [comment]
Thanks for responding! I have looked into the issue and cannot figure out what is causing the audio driver to revert to its previous state after restarting. The only way I can restore it back to a working state is by running your executable. This is such a niche issue that I can't find much about it online, and what I do find goes over my head. Whenever you get the chance, it would be nice to be able to run the audio fix separately. I'll continue looking into what is causing that, it doesn't seem to be a hardware issue.

**Comment by annabelsandford** [comment]
It could for example be an update-loop. Means that on boot or shutdown your device grabs a different driver from somewhere - this can for example come from a dependency or third party device. Headphones maybe? Anything. And yeah, this is so niche that I was even surprised somebody found this tool
